risc0/risc0-ethereum

.gitmodules

I added the `shallow` settings to `.gitmodules` in an effort to reduce the amount of data downloaded by `forge init -t risc0/bonsai-foundry-template`. It turns out not to really work, and partially breaks `forge init`. This PR removes those settings.

Remove shallow settings from .gitmodules

---

Cargo.lock
Cargo.toml

Bump version to `0.8.0-alpha.1` to mark development post custting of `release-0.7`

Bump Cargo versions to 0.8.0-alpha.1

---

README.md

Application developers should use the latest release, instead of main, to avoid encountering issues with verifying proofs produced by Bonsai, and other integration issues.
This PR adds a callout to alert users to this

Add callout to use the latest release instead of `main`

---

Cargo.lock
Cargo.toml
examples/erc20-counter/Cargo.lock
examples/erc20-counter/methods/guest/Cargo.lock
examples/erc20/Cargo.lock
examples/erc20/methods/guest/Cargo.lock

With release of `0.10`, bump version on `main` to `0.11.0-alpha.1`

Bump version to 0.11.0-alpha.1

---

Cargo.lock
Cargo.toml
steel/Cargo.toml

Pin revm-primitives to 3.1.0 for 0.10 release

Pin revm-primitives to 3.1.0 for 0.10 release

---

README.md

Cleaned up description of Steel and a few other minor changes to the readme

docs: readme polish

---

.github/workflows/main.yml
RELEASE.md
contracts/script/DeployVerifier.s.sol
contracts/src/RiscZeroCheats.sol
contracts/src/relay/BonsaiRelayTest.sol
contracts/test/RiscZeroGroth16Verifier.t.sol

This PR adds an initial version of release instructions to `RELEASE.md`.
It additionally adds a deploy script for the `RiscZeroGroth16Verifier` contract.
Resolves: https://github.com/risc0/risc0-ethereum/issues/76

Add initial version of release instructions

---

contracts/README.md
contracts/src/RiscZeroVerifierEmergencyStop.sol
contracts/version-management-design.md

This PR adds documentation describing the design of the verifier contract version management solution implemented in https://github.com/risc0/risc0-ethereum/pull/80. It is intended to provide detailed information to help security-minded application developers make an informed decision about how to use the verifier contracts.

Add documentation for the contract version management solution

---

contracts/src/IRiscZeroVerifier.sol
contracts/src/groth16/RiscZeroGroth16Verifier.sol
contracts/src/test/RiscZeroMockVerifier.sol
contracts/test/RiscZeroVerifierEmergencyStop.t.sol
contracts/test/RiscZeroVerifierRouter.t.sol

Rename `ReceiptClaimLib.from` to `ReceiptClaimLib.ok` to match recent API changes to `risc0`.
https://github.com/risc0/risc0/blob/c393f590b68cfd1dd0d8d167b9d6833ef832d428/risc0/zkvm/src/receipt_claim.rs#L68-L73

Rename ReceiptClaimLib.from to ReceiptClaimLib.ok

---

Cargo.toml
examples/erc20/README.md
steel/Cargo.toml
steel/README.md

This PR removes warnings about not being recommended for production use from all remaining places expect `risc0-steel` where the warning is softened.
It also bumps the development version to 1.1.0-alpha.1 to coincide with 1.0.0 release

Bump development version to 1.1.0-alpha.1 and remove warnings

---

contracts/script/Manage.s.sol
contracts/script/README.md
contracts/script/manage

- rename DeployEstopVerifier and change vm.startBroadcast() and vm.broadcast()
- move common functions to base contract
- simulate scheduled calls to avoid finding out they'll fail later
- add a codeblock language
- add --broadcast flag
- fix simulation, error on unset env var

Suggestions for #140

---

contracts/README.md

Closes: https://github.com/risc0/risc0-ethereum/issues/108

Refactor contract README.md

---

contracts/script/Manage.s.sol
contracts/script/README.md
contracts/script/manage
contracts/src/RiscZeroVerifierEmergencyStop.sol

Adds management scripts for the smart contracts.
[Quick link to readme](https://github.com/risc0/risc0-ethereum/tree/tcarstens/deploy/contracts/script)
Deployed to Sepolia:
* [Timelock](https://sepolia.etherscan.io/address/0xB4E3306129208cC8e6E75157f75f62eAe0B920a0#code)
* [Router](https://sepolia.etherscan.io/address/0x925d8331ddc0a1F0d96E68CF073DFE1d92b69187#code)
* [Estop](https://sepolia.etherscan.io/address/0xeA41bc40DAA1d0E681c7e8eA449b89a290e922e8#code)
* [Verifier](https://sepolia.etherscan.io/address/0x3d24C84FC1A2B26f9229e58ddDf11A8dfba802d0#code)

Add deployment + management scripts

---

steel/src/lib.rs

This fixes #144 by copying the Solidity struct from `contracts` into the
`sol!` macro.
This removes all external dependencies, but we need to make sure that
these two places always match.
Cherry-pick of #151 to release-1.0

Fix publishing of `risc0-steel` (#151)

---

Cargo.toml
steel/Cargo.toml
steel/src/mpt.rs

This PR moves the decoding of MPT nodes from [rlp](https://crates.io/crates/rlp) to [alloy-rlp](https://crates.io/crates/alloy-rlp).
This removes the `rlp` dependency and should be more performant. The behavior or the API of Steel is not changed.

chore: Decode MPT nodes using alloy

---

Cargo.toml

Steel requires at least version `0.3.7`.

fix: Set min `alloy-rlp` version to 0.3.7

---

steel/CHANGELOG.md
steel/src/host/db/alloy.rs
steel/src/host/db/mod.rs
steel/src/host/db/proof.rs
steel/src/host/db/provider.rs
steel/src/host/mod.rs

Makes the EIP-1186 proof request chunk size configurable in the builder.
closes WEB3-56

feat: configurable `eth_getProof` chunk size

---

steel/src/block.rs
steel/src/host/db/alloy.rs
steel/src/host/mod.rs

The `AlloyDb` is created for a specific block, and represents / queries the state with respect to that block.
This PR changes that reference from a block number to a block hash, which should prevent problems in weird situations like re-orgs or misconfigured RPCs.
This PR only changes the underlying representation, not the Steel API.

WEB3-103: chore: use block hash for the provider

---

README.md

Enhanced description for Steel to improve readability.

WEB3-104: Enhanced description for Steel

---

steel/README.md

This PR integrates the README improvements from #194 .
closes #181 
closes WEB3-22

WEB3-22: chore: Expand documentation on how to handle linking Steel proofs to verified block hashes

---

.github/workflows/bonsai.yml
.github/workflows/main.yml
Cargo.lock
Cargo.toml
contracts/src/groth16/RiscZeroGroth16Verifier.sol
examples/erc20-counter/Cargo.lock
examples/erc20-counter/Cargo.toml
examples/erc20-counter/methods/guest/Cargo.lock
examples/erc20-counter/methods/guest/Cargo.toml
examples/erc20/Cargo.lock
examples/erc20/Cargo.toml
examples/erc20/methods/guest/Cargo.lock
examples/erc20/methods/guest/Cargo.toml
examples/token-stats/Cargo.lock
examples/token-stats/Cargo.toml
examples/token-stats/methods/guest/Cargo.lock
examples/token-stats/methods/guest/Cargo.toml
steel/CHANGELOG.md
steel/Cargo.toml

This PR bumps the `risc0` dependencies to use the new 1.1.1 release, and accordingly bumps the version number to 1.1.1 for the workspace, and 0.13.1 for Steel.

Update dependencies and bump version to 1.1.1

---

steel/src/block.rs
steel/src/host/db/alloy.rs
steel/src/host/db/proof.rs
steel/src/mpt.rs
steel/src/state.rs

This fixes the current compilation errors.
Previously, we used to use `revm::primitives::HashMap` to have the same hash in Steel and `revm`. However, with the latest (minor) revm version, this has been switched to using `alloy_primitves::map::HashMap`. Thus, in this PR we also replace all `{Hash,BTree}{Map,Set}` with their more performant and specific equivalent in `alloy_primitives::map`.
- https://github.com/alloy-rs/alloy/issues/1365

WEB3-146: Replace map types with `alloy_primitives::map`

---

Cargo.lock
Cargo.toml
contracts/src/groth16/RiscZeroGroth16Verifier.sol
examples/erc20-counter/Cargo.lock
examples/erc20-counter/Cargo.toml
examples/erc20-counter/methods/guest/Cargo.lock
examples/erc20-counter/methods/guest/Cargo.toml
examples/erc20/Cargo.lock
examples/erc20/Cargo.toml
examples/erc20/methods/guest/Cargo.lock
examples/erc20/methods/guest/Cargo.toml
examples/governance/Cargo.lock
examples/governance/methods/guest/Cargo.lock
examples/token-stats/Cargo.lock
examples/token-stats/Cargo.toml
examples/token-stats/methods/guest/Cargo.lock
examples/token-stats/methods/guest/Cargo.toml
steel/CHANGELOG.md
steel/Cargo.toml

This PR bumps the `risc0` dependencies to use the new 1.1.2 release, and accordingly bumps the version number to 1.1.2 for the workspace, and 0.13.2 for Steel.

Update dependencies and bump risc0 to 1.1.2

---

steel/CHANGELOG.md
steel/src/mpt.rs

Assure that there are never trailing bytes stored in MPT leaves. This will never be the case for valid Ethereum MPTs

WEB3-159: Use `decode_exact` for MPT leaves

---

Cargo.lock
Cargo.toml
examples/erc20-counter/Cargo.lock
examples/erc20-counter/methods/guest/Cargo.lock
examples/erc20/Cargo.lock
examples/erc20/methods/guest/Cargo.lock
examples/governance/Cargo.lock
examples/governance/methods/guest/Cargo.lock
examples/token-stats/Cargo.lock
examples/token-stats/methods/guest/Cargo.lock
steel/Cargo.toml

This PR bumps the version number to 1.1.3 for the workspace, and 0.13.3 for Steel.

Update dependencies and bump version to 1.1.3

---

contracts/src/test/RiscZeroCheats.sol
ffi/src/lib.rs
ffi/src/main.rs
ffi/tests/basic.rs

This PR fixes an Abu encoding/decoding issue on the ffi prove command by replacing the tuple `(Bytes, Bytes)` with a `JournalSeal` struct

backport: Add `JournalSeal` struct to encode `ffi` `prove` output (#278)

---

Cargo.toml

With v0.8.6 alloy-core switched its default hasher to foldhash, which depends on rand and chrono. To avoid issues in the guest we pin the version to 0.8.5

WEB3-168: fix: pin alloy-core to v0.8.5

---

examples/erc20-counter/apps/src/bin/publisher.rs
examples/erc20/host/src/main.rs
examples/token-stats/host/src/main.rs
steel/src/beacon.rs
steel/src/block.rs
steel/src/contract.rs
steel/src/ethereum.rs
steel/src/host/builder.rs
steel/src/host/mod.rs
steel/src/lib.rs
steel/tests/corruption.rs

Previously, an input with a Beacon root commitment was created using the `into_beacon_input` method of the environment. This is inconsistent as all configuration should happen in the `EvmEnvBuilder`. 
Resolves #259 
Resolves WEB3-151

WEB3-151: Use builder also for beacon input

---

steel/README.md
steel/docs/how-does-steel-work.md

For example, changing a link which points to "examples/README.md" to "examples/" directly. In practice this will change the outcome as so:
From:
to:

WEB3-193: redirect README links to see both directories and README as well

---

steel/CHANGELOG.md
steel/src/host/mod.rs

`EvmEnvBuilder` is returned by the public method `EthEvmEnv::builder()`, so the type should also be public.

WEB3-209: Make `EvmEnvBuilder` public

---

steel/tests/corruption.rs

Otherwise the integration tests will fail to compile if the `unstable-history` feature is not enabled.

WEB3-229: fix: run history corruption tests only when the feature is enabled

---

RELEASE.md
contracts/deployment-test/Deployment.t.sol
contracts/deployment.toml
contracts/foundry.toml
contracts/src/config/Config.sol

Adds deployment tests that can be run against public networks to confirm that the setting and state recorded in `deployment.toml` are applied correctly.

WEB3-236: Add deployment tests to confirm deployment.toml against chain state

---

steel/docs/create-steel-app/create-steel-app

Addressing an error reported by one of our users, this PR ensures that the correct submodule commit will be checked out by `create-steel-app`.
This PR also:
* Uses the `${FOO:?}` env var syntax to make debugging unset env vars easier / more obvious.
* Adds a call to `git reset` to avoid having staged changes at the end of the script.

WEB3-238: Fix wrong submodule checkout error in create-steel-app script

---

RELEASE.md
contracts/script/README.md
examples/governance/README.md
steel/README.md
steel/docs/create-steel-app/README.md
steel/docs/what-is-steel.md

This pull request is all about refining the repository's documentation by eliminating pesky typos.
- **RELEASE.md**:  
- Replaced *"finsh"* with the correct *"finish"*.  
- **contracts/script/README.md**:  
- Upgraded *"sensative"* to *"sensitive"*.  
- **examples/governance/README.md**:  
- Promoted *"commited"* to *"committed"*.  
- **steel/README.md**:  
- Polished *"verfiably"* into *"verifiably"*.  
- **steel/docs/create-steel-app/README.md**:  
- Simplified phrasing by removing the duplicate: *"between between"* → *"between"*.  
- **steel/docs/what-is-steel.md**:  
- Refined: *"an smart contract"* to *"a smart contract"*.

fix:Typo Correction 

---

contracts/src/lib.rs
steel/src/lib.rs

One the common pieces of feedback we do from the Boundless private devnet was that `alloy` versioning was one of the biggest challenges. In particular, a developer would encounter a type mismatch error where "alloy::Foo is the not the same as alloy::Foo", which is a somewhat difficult to debug issue related to having two version of `alloy` in your crates tree. Because `alloy` is pre-1.0 and changing often, there is no silver bullet here.
One rule of thumb though is that an types that appear in the public interface of a crate should be (re-)exported from that crate. In our case, we do have `alloy` types in our public interface. So, if we apply this rule, we should export the types we use from `alloy`, and the easiest way to do so is to re-export the `alloy` crate. This helps with the …

WEB3-240: Re-export alloy from risc0-ethereum-contracts and risc0-steel

---

.github/workflows/main.yml

- Artifacts actions `@v3` being deprecated.
- All `actions/upload-artifact` and `actions/download-artifact` uses must be upgraded to `@v4` before brownout dates in January:
- https://github.blog/changelog/2024-11-05-notice-of-breaking-changes-for-github-actions/

WEB3-243: Upgrade Artifacts Actions using `@v3` to `@v4`

---

.github/scripts/cargo-clippy.sh
.github/scripts/cargo-test.sh
.github/workflows/main.yml
RELEASE.md

I tested this PR by opening https://github.com/risc0/risc0-ethereum/pull/342. Looking at https://github.com/risc0/risc0-ethereum/pull/342/checks, we expect the CI jobs to fail.

WEB3-242: Add --locked to release branch cargo runs

---

.github/actions/cargo-risczero-install/action.yaml
.github/workflows/e2e.yml
.github/workflows/main.yml

I started seeing the following errors in our CI, and realized that we do not apply `--locked` when building `cargo-risczero` from `main`. This would be good to help with stability of CI.
https://github.com/risc0/risc0-ethereum/actions/runs/12078623988/job/33683295704?pr=346

WEB3-245: Use --locked to build cargo-risczero from main in CI

---

.github/actions/cargo-risczero-install/action.yaml
.github/workflows/e2e.yml
.github/workflows/main.yml
contracts/deployment-test/Deployment.t.sol
contracts/deployment.toml
contracts/script/Manage.s.sol
contracts/script/README.md
contracts/src/RiscZeroSetVerifier.sol
contracts/src/config/Config.sol

- **WEB3-243: Upgrade Artifacts Actions using `@v3` to `@v4` (#343)**
- **WEB3-245: Use --locked to build cargo-risczero from main in CI (#348)**
- **WEB3-244: Add set verifier deployment (#345)**

Cherry-pick #343 #348 and #345 to release-1.2

---

.github/workflows/main.yml
aggregation/Cargo.toml
aggregation/guest/set-builder/Cargo.toml
aggregation/src/lib.rs
aggregation/src/receipt.rs

This PR resolves issues with publishing `risc0-aggregation` stemming from dependency on the `set-builder` guest through Cargo.
It does so by removing usage of that guest, which is in the form of all code dependending on `SET_BUILDER_ID` or `SET_BUILDER_ELF`.
In practice, these values are difficult to use anyway, because they need to align with an on-chain verifier. Unless reproducible builds are always used, these values will flucuate.
There is an open issue on how to better manage these values.
Related https://github.com/risc0/risc0-ethereum/issues/353

WEB3-254: Remove dependencies of set-builder-guest to allow publishing to crates.io

---

.github/workflows/main.yml
Cargo.lock
aggregation/Cargo.toml
aggregation/guest/Cargo.toml
aggregation/guest/set-builder/Cargo.lock
aggregation/guest/set-builder/Cargo.toml
aggregation/src/lib.rs
aggregation/src/receipt.rs

This PR resolves issues with publishing `risc0-aggregation` stemming
from dependency on the `set-builder` guest through Cargo.
It does so by removing usage of that guest, which is in the form of all
code dependending on `SET_BUILDER_ID` or `SET_BUILDER_ELF`.
In practice, these values are difficult to use anyway, because they need
to align with an on-chain verifier. Unless reproducible builds are
always used, these values will flucuate.
There is an open issue on how to better manage these values.
Related https://github.com/risc0/risc0-ethereum/issues/353

Chery-pick: Remove dependencies of set-builder-guest to allow publishing to crates.io (#354)

---

contracts/src/IRiscZeroSetVerifier.sol
contracts/src/RiscZeroSetVerifier.sol
contracts/test/RiscZeroSetVerifier.t.sol

It seems that only the parameters marked with indexed become topics that we can filter on. Non-indexed parameters are encoded as part of the data payload of the log entry and cannot be used for filtering.
It also adds the seal as part of the event as unfortunately, in cases where the event gets triggered by an internal transaction, for instance when using `submitRootAndFulfillBatch` the call data of the method is not available from the original transaction

WEB3-261: Index root in VerifiedRoot

---

contracts/deployment.toml
contracts/src/RiscZeroVerifierRouter.sol

Corrected `Apperent` to `Apparent`
Corrected `associatied` to `associated` x2.

fix: typos in documentation files

---

Cargo.toml
steel/Cargo.toml
steel/src/mpt.rs

Using re-exported to avoid issues if they make semver breaking changes in future.
Also increased the minimum patch version to be safe, but opinionated if this should be removed or only applied to `steel` as the minimum patch might break in edge case usages. Happy to revert this

WEB3-275: switch nybbles to use re-exported type from alloy-trie

---

build/src/lib.rs
examples/erc20-counter/apps/src/bin/publisher.rs
examples/token-stats/host/src/main.rs
examples/token-stats/methods/guest/src/main.rs
steel/docs/create-steel-app/README.md
steel/docs/create-steel-app/create-steel-app
steel/src/block.rs
steel/src/history/mod.rs
steel/src/host/db/mod.rs
steel/src/host/db/proof.rs
steel/src/host/mod.rs
steel/src/lib.rs
steel/src/state.rs

* updated create-steel-app to use 1.2 by default
* also added a line to the README to make sure that Foudry is updated to avoid a relatively old bug (most end users should be fine, but I ran into this issue)

WEB3-281: update create-steel-app to 1.2

---

steel/docs/steel-history.md

Note on how I broke up paragraphs onto multiple lines. It's not a huge benefit in this PR, but splitting up paragraphs helps with reviews for changes later because the diff will show the changes in a nicer way. In prose like this, I prefer to break up paragraphs with one sentence or clause per line. I find that works well for collaborative editing.

suggestions for the steel-history.md doc

---

Cargo.lock
Cargo.toml
aggregation/guest/set-builder/Cargo.lock
aggregation/guest/set-builder/Cargo.toml
examples/erc20-counter/Cargo.lock
examples/erc20-counter/Cargo.toml
examples/erc20-counter/methods/guest/Cargo.lock
examples/erc20-counter/methods/guest/Cargo.toml
examples/erc20/Cargo.lock
examples/erc20/Cargo.toml
examples/erc20/methods/guest/Cargo.lock
examples/erc20/methods/guest/Cargo.toml
examples/governance/Cargo.lock
examples/governance/Cargo.toml
examples/governance/methods/guest/Cargo.lock
examples/governance/methods/guest/Cargo.toml
examples/token-stats/Cargo.lock
examples/token-stats/Cargo.toml
examples/token-stats/methods/guest/Cargo.lock
examples/token-stats/methods/guest/Cargo.toml
ffi/guests/echo/Cargo.lock
ffi/guests/echo/Cargo.toml

- **update Cargo.toml files**
- **update Cargo.lock files**

Bump risc0 monorepo dependencies and version number to 1.2.1

---

contracts/deployment-test/Deployment.t.sol
contracts/deployment.toml
contracts/script/Manage.s.sol

Timelock controller execute transactions have now cleared, and so the 1.2 verifiers are live on mainnets.

WEB3-294: Update deployment.toml to mark 1.2 mainnet verifiers as routable

---

.github/actions/cargo-risczero-install/action.yaml

Developed to address a challenge in the release process when the remote release-1.2 branch is on an rc version, as this causes incompatibility for client-server (r0vm).

WEB3-295: Add option to install from crates.io for cargo-risczero-install action

---

README.md
examples/README.md

Fixes a broken link to the Steel directory and moves the examples directory link up to the examples directory instead of the `examples/erc20-counter` directory.

WEB3-306: docs: fix broken link and link to examples

---

crates/aggregation/guest/build.rs

https://github.com/risc0/risc0/pull/2762 changed the way GuestOptions are constructed. This PR fixes this and switches to the new builder pattern.

WEB3-326: fix: Use a builder pattern for GuestOptions and DockerOptions

---

examples/erc20-counter/methods/build.rs
examples/governance/methods/build.rs

https://github.com/risc0/risc0/pull/2762 changed the way GuestOptions are constructed. This PR fixes this and switches to the new builder pattern.

WEB3-328: fix: Use a builder pattern for GuestOptions and DockerOptions

---

.github/workflows/steel-documentation.yml
crates/steel/README.md
crates/steel/src/contract.rs

This deploys a custom docs.rs like doc site for steel using GitHub pages and `cargo doc`

WEB3-321: feat: deploy steel docs on github pages

---

crates/steel/src/host/builder.rs
crates/steel/src/host/mod.rs
crates/steel/src/verifier.rs
crates/steel/tests/corruption.rs
examples/erc20-counter/apps/src/bin/publisher.rs

WEB3-282: feat: Allow querying blocks by hash

---

crates/steel/src/host/builder.rs

The doctest gets included even though the corresponding method is behind a feature using `#[stability::unstable(feature = "history")]`. This leads to failing tests if the `unstable-history` feature is not enabled.
Fixed by adding a hidden `#[cfg(feature = "unstable-history")]` to the example, in the docs it still looks like the following:
```rust
let commitment_hash = B256::from_str("0x1234...")?;
let builder = EthEvmEnv::builder()
.rpc(Url::parse("https:// ethereum-rpc. publicnode. com")?)
.beacon_api(Url::parse("https:// ethereum-beacon-api. publicnode. com")?)
.block_number(1_000_000);  // execute against historical state
let builder = builder.commitment_block_hash(commitment_hash); // commit to recent block
let env = builder.build().await?;
```

WEB3-333: fix: `unstable-history` doctest

---

examples/governance/instructions.md

Fixed a broken link to a benchmark contract which was moved to `contracts/test`

fix: broken contract link in examples

---

.github/workflows/main.yml

Recently, we had the `risc0` CI failing, because `cargo test` was behaving differently from `cargo test --all-features`.
This PR adds a plain `cargo test` to the CI to better catch these failures.

WEB3-334: chore: Add CI run of cargo test without features

---

crates/trie/Cargo.toml

The recently released 0.4.3 of `munge` fixes issues with the previous 0.4.2, so the additional locked dependency is no longer needed.

WEB3-361: chore: Remove `munge` dependency

---

Cargo.toml
crates/op-steel/Cargo.toml
examples/op/l1-to-l2/methods/guest/Cargo.toml
examples/op/l2-to-l1/methods/guest/Cargo.toml
examples/op/l2/methods/guest/Cargo.toml
rust-toolchain.toml

Starting with op-alloy 0.10.7 rust 1.81 is required which is not yet supported in the guest.

WEB3-364: fix: limit op-alloy version to maintain Rust 1.81 support

---

.github/actions/cargo-risczero-install/action.yaml
rust-toolchain.toml

In the cargo-risczero-install action, specifically the path using the version (rather than the ref) the r0vm installation was missing

WEB3-367: Install r0vm

---

crates/ffi/src/main.rs
crates/op-steel/src/l1.rs

"in the OP network" → "on the OP network"
(Correct use of the preposition "on" when referring to a network.)
"hex encoded" → "hex-encoded"
(Added a hyphen according to English grammar rules.)
"Take stdout is ensure no extra data is written to it." → "Take stdout to ensure no extra data is written to it."
(Fixed grammatical error: "is ensure" → "to ensure".)
"The hex encoded input to provide to the guest binary" → "The hex-encoded input to provide to the guest binary"
(Added a hyphen for proper compound adjective usage.)

Grammar and Style Fixes in Code Comments and Documentation

---

crates/steel/src/host/mod.rs

The latest block is evaluated when the `.build` is called, in rare cases this could lead to the situation where env1 and env2 correspond to different blocks. This fixes this rare issue in the tests by setting the block hash explicitely.

WEB3-368: chore: fix consistency in `extend` doctest

---

crates/steel/src/host/mod.rs

The latest block is evaluated when the `.build` is called, in rare cases this could lead to the situation where env1 and env2 correspond to different blocks. This fixes this rare issue in the tests by setting the block hash explicitely.

Backport 465

---

crates/steel/src/contract.rs

Enhance documentation for Contract::call_with_prefetch method to better explain its purpose, benefits, and trade-offs. This addresses issue #387.
- Add detailed explanation of how call_with_prefetch helps reduce preflight time by minimizing RPC calls
- Document trade-offs with certain node software (e.g., Geth vs Reth)
- Add usage examples for both call_with_prefetch and prefetch_access_list methods
- Update Contract struct documentation to recommend call_with_prefetch for calls with many storage accesses
- Clarify relationship between prefetch_access_list and call_with_prefetch methods

docs: Improve documentation of Contract::call_with_prefetch

---

crates/ffi/src/main.rs
examples/erc20-counter/apps/src/bin/publisher.rs
examples/governance/apps/src/bin/publisher.rs
examples/op/l1-to-l2/src/main.rs
examples/token-stats/host/src/main.rs

This PR updates deprecated `#[clap(...)]` attributes to their modern equivalents in `clap` 4.x.
The current codebase still uses outdated syntax that has been deprecated since version 4.0.
By making this update, we ensure compatibility with future versions and maintain code quality.
Fixes #480

refactor: Clap attribute macros from #[clap(...)] to #[arg(...)] and #[command(...)] in v4.x

---

contracts/src/test/RiscZeroMockVerifier.sol
examples/governance/contracts/src/RiscZeroGovernorCounting.sol

This PR includes the following changes:
- Fixes a typo in RiscZeroMockVerifier.sol by changing "it's" to "its" in the comments
- Updates the copyright year from 2024 to 2025
- Minor formatting improvements in comments
These changes help maintain code quality and ensure proper documentation.

Fix typo in RiscZeroMockVerifier comments and update copyright year

---

.github/actions/cargo-risczero-install/action.yaml
.github/workflows/linear.yml
.github/workflows/main.yml

This PR skips the Linear workflow (requiring `secrets.LINEAR_API_KEY`) and the example verify step (requiring `secrets.ALCHEMY_RISC0_ETH_API_KEY`) in PRs from forks.

WEB3-362: chore: Run actions requiring secrets not from forks

---

contracts/src/groth16.rs
contracts/src/receipt.rs

Fix a bug related to `decode_seal`, by not requiring verifier parameters when decoding a FakeReceipt

WEB3-380: Fix decode_seal

---

Cargo.lock
Cargo.toml
contracts/src/groth16.rs
contracts/src/receipt.rs
examples/erc20-counter/Cargo.lock
examples/governance/Cargo.lock
examples/op/Cargo.lock

Fix a bug related to `decode_seal`, by not requiring verifier parameters when decoding a FakeReceipt
Bump version to v.1.4.1

WEB3-380: Fix decode_seal (#494)

---

examples/op/l1-to-l2/src/main.rs

Using the latest safe block sometimes resulted in selecting a block that was too new; this has now been changed to the latest finalized block.

WEB3-391: chore: Make OP `l1-to-l2` test more robust.

---

examples/op/l1-to-l2/src/main.rs

Using the latest safe block sometimes resulted in selecting a block that was too new; this has now been changed to the latest finalized block.

WEB3-391: chore: Make OP `l1-to-l2` test more robust. (#512)

---

crates/steel/src/host/db/proof.rs
crates/steel/tests/steel.rs

Fixes a problem where Steel account queries without bytecode were not properly recorded and thus did not appear in the input. This PR also adds a test that previously failed.

WEB3-401: fix: Steel account queries (#529)

---

crates/op-steel/src/optimism/host.rs
examples/op/l1-to-l2/src/main.rs
examples/op/l2-to-l1/src/main.rs

The following now returns the correct dispute game commit:
```rust
let builder = OpEvmEnv::builder()
.dispute_game_from_rpc(
optimism_portal,
Url::parse(l1_rpc_url).expect("Failed to parse RPC URL"),
)
.game_index(DisputeGameIndex::Finalized);
let op_env = builder
.rpc(Url::parse(l2_rpc_url).expect("Failed to parse RPC URL"))
.build()
.await
.expect("Failed to build OP-EVM environment");
let op_env_commitment = op_env.commitment();
```

WEB3-405: op-steel: Return correct commit for host env

---

SECURITY.md

There are four hyphens at the beginning of a PGP block instead of five. The correct form is: `-----BEGIN PGP PUBLIC KEY BLOCK-----`

minor docstring fixups

---

contracts/deployment.toml
contracts/src/RiscZeroSetVerifier.sol
contracts/src/selector.rs

This is a cherry-pick of commit a452059 and 728ec4b. These were made to the `release-2.0` branch.
- **Deploy SetVerifierV0_5 (#533)**
- **Add SetVerifierV0_6**

WEB3-439: Update deployment.toml and selectors library with commits made to release-2.0

---

contracts/script/Manage.s.sol

The old tutorial URL returned 404. Updated it to the new canonical page:
https://book.getfoundry.sh/guides/scripting-with-solidity

docs: replace outdated Foundry scripting link

---

Cargo.toml
crates/op-steel/Cargo.toml
crates/steel/Cargo.toml

With default features, alloy pulls in `native-tis` dependencies:
```console
cargo tree | grep native-tls
│   │   │   │   │   ├── native-tls v0.2.14
│   │   │   │   │   ├── tokio-native-tls v0.3.1
│   │   │   │   │   │   ├── native-tls v0.2.14 (*)
│   │   │   │   ├── native-tls v0.2.14 (*)
│   │   │   │   ├── tokio-native-tls v0.3.1 (*)
```

WEB3-512: Disable alloy default features

---

.github/workflows/steel-documentation.yml

cargo doc requires edition2024, so the nightly needs to be updated to fix the failing documentation deploys.

WEB3-516: fix: Steel documentation workflow

---

contracts/deployment-test/Deployment.t.sol
contracts/deployment.toml
contracts/script/README.md

Due to a constraints error in the division circuit in the zkVM, detailed in https://github.com/risc0/risc0/security/advisories/GHSA-f6rc-24x4-ppxp , the `risc0-zkvm 2.1` verifiers have had their estop activated.
This PR marks the verifiers as stopped in `deployment.toml`.
We also fix an issue with deployment to Avalance Fuji

WEB3-521: Mark risc0-zkvm 2.1 verifiers as stopped

---

README.md

This PR removes the dead reference-style link `[examples directory]` from README.

Remove dead examples link

---

contracts/deployment.toml
contracts/script/README.md
contracts/src/selector.rs

Due to https://github.com/risc0/risc0/security/advisories/GHSA-jqq4-c7wq-36h7 , set verifier deployments prior to 0.9 are vulnerable. All deployments have now been disabled, and this PR updates the deployment.toml to reflect this.

WEB3-545: Mark set verifiers prior to 0.9 as stopped
